removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;

player forceAddUniform "U_I_FullGhillie_sard";
for "_i" from 1 to 3 do {player addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 3 do {player addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 3 do {player addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 3 do {player addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 3 do {player addItemToUniform "ACE_morphine";};
player addItemToUniform "ACE_MapTools";
player addItemToUniform "ACE_Flashlight_XL50";
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
for "_i" from 1 to 2 do {player addItemToUniform "R3F_15Rnd_9x19_HKUSP";};
for "_i" from 1 to 2 do {player addItemToUniform "SMA_30Rnd_556x45_M855A1";};
player addVest "V_PlateCarrierIA2_dgtl";
for "_i" from 1 to 9 do {player addItemToVest "rhs_mag_30Rnd_556x45_Mk262_Stanag";};
player addBackpack "B_Carryall_oli";
player addItemToBackpack "RKSL_optic_PMII_525_wdl";
player addItemToBackpack "UK3CB_BAF_Silencer_L115A3";
player addItemToBackpack "ACE_microDAGR";
player addItemToBackpack "ACE_ATragMX";
player addItemToBackpack "ACE_RangeCard";
player addItemToBackpack "UK3CB_BAF_L115A3_Ghillie";
for "_i" from 1 to 10 do {player addItemToBackpack "UK3CB_BAF_338_5Rnd";};
player addHeadgear "H_HelmetIA";

player addWeapon "SMA_HK416CQB_vfg_ODPAINTED";
player addPrimaryWeaponItem "SMA_supp2BOD_556";
player addPrimaryWeaponItem "FHQ_optic_AC11704";
player addWeapon "R3F_HKUSP";
player addHandgunItem "muzzle_snds_L";
player addWeapon "Binocular";

player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "tf_anprc148jem";
[player,"tacs_Insignia_SpartanHelmet_Black"] call bis_fnc_setUnitInsignia;
